name: Deployment

on:
  push:
    tags:
      - v*

jobs:
  test:
    name: Build on ${{ matrix.os }}, Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3

      - name: Additional info about the build
        shell: bash
        run: |
          uname -a
          df -h
          ulimit -a

      - uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: devtools/conda-envs/deployment_env.yaml
          environment-name: test
          channels: conda-forge
          extra-specs: |
            python=${{ matrix.python-version }}

      - name: Install package
        shell: bash -l {0}
        run: |
          python -m pip install . --no-deps
          micromamba list

      - name: Conda Build and Upload
        shell: bash -l {0}
        working-directory: ./devtools/conda-recipes/anaconda
        run: |
          export CVPACK_VERSION=${{ github.ref_name }}
          echo "::group::Building conda package for cvpack $CVPACK_VERSION"
          outdir=$(mktemp -d)
          conda mambabuild . --no-anaconda-upload -c conda-forge --output-folder $outdir
          echo "::endgroup::"
          echo "::group::Uploading package to mdtools conda channel"
          PACKAGE=$(find $outdir -name *.tar.bz2 | head -1)
          export ANACONDA_API_TOKEN=${{ secrets.ANACONDA_TOKEN }}
          anaconda upload --user mdtools --force --label main $PACKAGE
          echo "::endgroup::"

      - name: PyPI Build and Upload
        shell: bash -l {0}
        run: |
          export CVPACK_VERSION=${{ github.ref_name }}
          echo "::group::Building PyPI distribution for cvpack $CVPACK_VERSION"
          python -m build
          python -m twine upload -u __token__ -p ${{ secrets.PYPI_TOKEN }} --repository pypi dist/*
          echo "::endgroup::"
